baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Rouzbeh Pirayadi"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Rouzbeh Pirayadi"
  description: Personal Infromation about me
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"
  favicon2: "/logo2.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/logo2.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Rouzbeh Pirayadi" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Rouzbeh Pirayadi."
    subtitle: ""
    content: "I am a computer engineering student in Sharif University of Technology."
    image: /images/rouzbeh.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "./CV_Rouzbeh_Pirayadi"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/rpirayadi
        - icon: fa fa-envelope
          url: mailto:rouzbehpirayadi@gmail.com
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/rouzbeh.jpg"
    content: |-
      I received my diploma in Mathematics and Physics major from Allameh Helli High School, and my bachelors in Computer Engineering from Sharif University of Technology, the most prestigieous university in Iran.
      I was ranked 5th among approximately 200 students.

      I am interested in AI accelerators, process in memory techniques, and other computer architecture and AI related topics. 

    skills:
      enable: true
      title: "Here are a few tools and technologies I've worked with:"
      items:
        - "Python"
        - "Java"
        - "C/C++"
        - "Verilog"
        - "Pytorch"
        - "Xilinx"
        - "Torchhd"
        - "Android"
        - "Swift"
        - "PostgreSQL"


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Engineering"
        school:
          name: "Sharif University of Technology"
          url: "https://en.sharif.edu/"
        date: "2019 - 2023"
        GPA: "19.73 out of 20.0"
        content: |-
          #### Notable Courses
          - Computer Architecture (20.0/20.0)
          - Artificial Intelligence (20.0/20.0)
          - Machine Learning (20.0/20.0)
          - Digital Systems Design (20.0/20.0)
          - Operating Systems (20.0/20.0)
          - Embedded Systems (20.0/20.0)
          - Algorithm Design (20.0/20.0)
          - Linear Algebra (20.0/20.0)
          - Engineering Probability and Statistics (19.6/20.0)

          #### Teaching Assistant Experiences

          - Artificial Intelligence, Prof. Mohammad Hossein Rohban    (fall 2023)

          - Embedded Systems, Prof. Mohsen Ansari                     (fall 2023)

          - Operating Systems, Prof. Hossein Asadi                   (fall 2023)

          - Programming language, Prof. Mohammad Izadi                  (fall 2023)

          - Numerical Computation, Prof. Samira Hossein Ghorban           (fall 2023)

          - Artificial Intelligence, Prof. Mohammad Hossein Rohban    (spring 2023)

          - Embedded Systems, Prof. Mohsen Ansari                     (spring 2023)

          - Linear Algebra, Prof. Hamid R. Rabiee, Prof. Maryam Ramezani (spring 2023)

          - Computer Structure and language, Prof. Hossein Asadi (fall 2022)

          - Embedded Systems, Prof. Mohsen Ansari (fall 2022)

          - Linear Algebra, Prof. Hamid R. Rabiee, Prof. Maryam Ramezani (fall 2022) 

          - Linear Algebra, Prof. Hamid R. Rabiee, Prof. Maryam Ramezani (spring 2022)

          - Logic Design, Prof. Laleh Arshadi (fall 2021)
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      - title: "High School"
        school:
          name: "Allameh Helli High School"
          url: ""
        date: "2016 - 2019"
        GPA: "19.93 out of 20.0"
        content: |-
          Allameh Helli Schools, named after Al-Hilli, are schools found in various cities of Iran as part of the National Organization for Development of Exceptional Talents.

        # featuredLink:
        #   enable: true
        #   url: "https://example.com"


  # Experience
  experience:
    enable: true
    # title: "Research Experience"
    info:
      - enable: false
    items:
      - job: "Process in DRAM for hyperdimensional computing"
        company: "Research Experience"
        companyUrl: ""
        date: "March 2023 - present"
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        content: "I am participating in a project under supervision of Nezam Rohbani and Prof. Hamid Sarbazi-Azad. The goal of the project to
        make possible doing hyperdimensional operations in different memories, mostly DRAM. "

      - job: "Software developer at Onyxlab"
        company: "Working Experience"
        companyUrl: ""
        date: "June 2022 - August 2022"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        content: "I worked as a software developer for my internship program at Onyxlab."
        
        # info:
        #   enable: true
        #   content: I worked as a software developer for more than one year in Amazon.
        # content: |
        #   I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

        #   - Lead backend developer for a product.
        #   - Created a frontend design for a product.

      # - job: "Junior Software Developer"
      #   company: "Apple"
      #   companyUrl: "https://example.com"
      #   date: "Jan 2020 - Aug 2020"
      #   info:
      #     enable: false
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "UI/UX Designer"
      #   company: "Netflix"
      #   companyUrl: "https://example.com"
      #   date: "June 2017 - Nov 2019"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."



  # Achievements
  achievements:
    enable: true
    title: "Honors and Awards"
    items:
      - title: Direct Master's Admission
        content: I got admitted to AI/ML M.Sc. with Brilliant Talent Award.
      - title: Top Student in UEE
        content: I was ranked 80 in University Entrance Exam (UEE aka konkour) among ~15,000 participants
      - title: Student at NODET
        content: I was admitted to NODET (National Organization for Development of Exceptional Talents)

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: MIPS
        content: Simulating a minimal mips-like processor using schematic section of quartus. The memory is simulated using verilog and waveforms have been extracted.
        image: /images/projects/mips.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Quartus"
          - "Verilog"
        links:
          - icon: fab fa-github
            url: https://github.com/rpirayadi/MIPS

      - title: Matmul
        content: A verilog simulation of a matrix multiplier which devides matrices into smaller blocks. Smaller blocks' result is 
                  calculated using a combinational circuit. Then the whole result is calculated sequentially.
        image: /images/projects/matmul.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Verilog"
          - "Xilinx"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter


      - title: Online Shop
        content: An instance of an online shop, with different features such as sale, auctions, filtering, favorite products and shopping cart.
        image: /images/projects/shop.png
        featured:
          name: Demo Video
          link: https://hugo-profile.netlify.app
        badges:
          - "Java"
          - "Javafx"
          - "SQLite"
          - "Maven"

        links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/AdvProg2020/Project_team-34
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: TimeSync
        content: An android app to manage meeting and teams. Meetings could be created by admins and people in the group can vote for the time.
        image: /images/projects/Time2.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Android"
          - "Java"
        links:
          - icon: fab fa-github
            url: https://github.com/s0heil20/TimeSync

      - title: Smart Pot
        content: A web app and mobile app created by flutter that connects to an embedded system in a pot. This systems monitors 
            the temperature, humidity and water level and visualizes them for the user.

        image: /images/projects/pot.png
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Raspberry pi"
          - "Arduino"
          - "Django"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Sec Chat
        content: A program that enables chating between clients and satisfies many security requirments. 
            Namely, the application satisfies forward and backward secrecy, confidentiality, end-to-end encrypted message.
            In order to do so, double ratchet algorithm is utilized.
        image: /images/projects/ratchet.svg
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Python"
          - "Crypto"
        links:
          - icon: fab fa-github
            url: https://github.com/AryanAhadinia/SecChat

      - title: Shrive
        content: A web application similar to google drive. This application provides file storing, folder mangement, categories and file sharing
          between different users.
        image: /images/projects/shrive.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Python"
          - "Django"
          - "html"
          - "css"
        links:
          - icon: fab fa-github
            url: https://github.com/sudoparsa/content-management-system

      - title: Queue Simulator
        content: A program that simulates an M/M/1 queue and calculates many parameters such as average queue length, average waiting time and etc.
        image: /images/projects/mm1.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/rpirayadi/Queue-Simulation

      - title: Multi-threaded web server
        content: A web server that handles each client in a seperated thread.
        image: /images/projects/Multiserver.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/rpirayadi/OS-proj







  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: rouzbehpirayadi@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
